apiVersion: v1
kind: Service
metadata:
  name: express-sqlite-app-loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: express-sqlite-app
