apiVersion: v1
kind: Service
metadata:
  name: express-sqlite-app-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 80 # Port du service
      targetPort: 3000 # Port auquel le service redirige
      nodePort: 31000 # Port accessible depuis l'extérieur du cluster (entre 30000 et 32767)
  selector:
    app: express-sqlite-app
